#!/usr/bin/env zsh

# Get the working git branch when possible.
branchinfo() {
    gitbr=$(git branch 2>/dev/null | sed -ne 's/^\* \(.*\)/ ⌥ \1/p')
    if ! [ -z $gitbr ]; then
        echo $gitbr
    else
        dotbr=$(dot branch 2>/dev/null | sed -ne 's/^\* \(.*\)/ ⌥ \1/p')
        # Only show the status of my dotfile repo when I'm in `.dots`.
        if ! [ -z $dotbr ] && [ $(pwd) = "$HOME/.dots" ]; then
            echo $dotbr
        fi
    fi
}


# vim:tw=79:ts=8:sts=4:sw=4:et:
