#!/usr/bin/env zsh

# Get the active python virtual environment when possible.
venvinfo() {
    if ! [ -z "$VIRTUAL_ENV" ]; then
        echo " ∫ "$(basename "$VIRTUAL_ENV")
    fi
}


# vim:tw=79:ts=8:sts=4:sw=4:et:
