#!/usr/bin/env zsh
# Generate a .pdf file from LaTeX.
#
#   Usage: tex2pdf /path/to/source.tex

if [[ "$#" -eq 1 ]]; then # if exactly 1 arg (path to .tex file to compile)...
    if [[ -a "$1" ]]; then # if the file exists...
        local abspath=$(realpath "$1") # absolute path to input file
        if [[ "${abspath: -4}" == ".tex" ]]; then # and it's a .tex file...
            local texpath=$(dirname "$abspath") # directory containing .tex file
            local texfile=$(basename "$abspath") # name of .tex file
            local texname=$(basename "$texfile" '.tex') # name of .tex file without extension
            local pdflatex_args=(
                "--interaction=nonstopmode"
            )

            cd "$texpath"

            # printf 'compiling...'
            # generates .aux, .bcf, .log, .out, .pdf, .run.xml, and .toc files
            pdflatex "$pdflatex_args[@]" "$texfile" 1>/dev/null
            if [[ "$?" -ne 0 ]]; then # if pdflatex returned an error value...
                echo "error: pdflatex failed to generate .pdf from "$abspath""
                cd - 1>/dev/null
                return 1
            fi
            local exts=('.aux' '.bcf' '.log' '.out' '.run.xml' '.toc')

            # printf 'generating bibliography...'
            # generates .bbl and .blg files
            biber "$texname" 1>/dev/null
            if [[ "$?" -ne 0 ]]; then # if biber returned an error value...
                echo "error: biber failed to generate bibliography for "$abspath""
                cd - 1>/dev/null
                return 1
            fi
            exts+=(".bbl" ".blg")

            # i'm not sure why it's necessary to run pdflatex twice, but it is
            pdflatex "$pdflatex_args[@]" "$texfile" 1>/dev/null
            pdflatex "$pdflatex_args[@]" "$texfile" 1>/dev/null
            if [[ "$?" -ne 0 ]]; then # if pdflatex returned an error value...
                echo "error: pdflatex failed to generate .pdf from "$abspath""
                cd - 1>/dev/null
                return 1
            fi

            # printf "cleaning up..."
            # Delete intermediary files
            for ext in "$exts[@]"; do
                rm -f "$texname""$ext"
            done
        else
            echo "error: file "$abspath" is not a LaTeX source file"
            cd - 1>/dev/null
            return 1
        fi
    else
        echo "error: file "$1" not found"
        cd - 1>/dev/null
        return 1
    fi
else
    echo "usage: tex2pdf /path/to/source.tex"
    cd - 1>/dev/null
    return 1
fi

# printf "done.\n"
cd - 1>/dev/null
return 0
