#!/usr/bin/env zsh
# -----------------------------------------------------------------------------
# Compile a LaTeX document.
#
#   Usage: tex2pdf FILENAME
# -----------------------------------------------------------------------------

# If exactly 1 argument...
if [[ "$#" -eq 1 ]]; then
    # If the source file exists...
    if [[ -a "$1" ]]; then
        local tex="${1%%.*}" # name of .tex file without extension

        # Generates .aux, .bcf, .log, .out, .pdf, .run.xml, and .toc files
        pdflatex --halt-on-error "${tex}".tex 1>/dev/null
        if [[ "$?" -ne 0 ]]; then
            return 1
        fi
        local exts=(".aux" ".bcf" ".log" ".out" ".run.xml" ".toc")

        # Generates .bbl and .blg files
        biber "${tex}" 1>/dev/null
        if [[ "$?" -ne 0 ]]; then
            return 1
        fi
        exts+=(".bbl" ".blg")

        # I'm not sure why it's necessary to run `pdflatex' twice, but it is
        pdflatex --halt-on-error "${tex}".tex 1>/dev/null
        pdflatex --halt-on-error "${tex}".tex 1>/dev/null
        if [[ "$?" -ne 0 ]]; then
            return 1
        fi

        # Delete intermediary files
        for ext in "${exts[@]}"; do
            rm -f "${tex}""${ext}"
        done
    else
        return 1
    fi
else
    return 1
fi

return 0
